---

- name: Install python dependencies
  apt:
    name:
      - libffi-dev
      - python3-dev
      - python3-pip
      - libpq-dev
    update_cache: yes
    state: latest
  tags: packages

- name: Install virtualenv
  command: pip3 install virtualenv

# Create worker user
- user: name=worker shell=/bin/bash

- name: Add worker to sudoers file
  lineinfile: "dest=/etc/sudoers state=present regexp='^worker' line='worker ALL=(ALL) NOPASSWD: ALL'"

- name: Create folder for worker files
  file: path={{ worker_working_dir }} owner=worker group=worker state=directory

- name: Create folder for worker log files
  file: path={{ worker_log_dir }} owner=worker group=worker state=directory

# Install supervisor
- apt: name=supervisor update_cache=yes state=present

- name: Start supervisor service
  service: name=supervisor state=started
