# # Install requirements for task runner
# - apt: name=libffi-dev
# - pip: requirements={{ application_dir }}/requirements.txt virtualenv={{ web_virtualenv }}
#   become_user: klee_web

# - name: Copy supervisor config file
#   template: src=supervisor_web.conf.j2 dest=/etc/supervisor/conf.d/web.conf

# - name: Copy admin password script
#   template: src=admin_psw.sh.j2 dest=/src/web/admin_psw.sh

# - name: Get bower dependencies
#   shell: bower install --config.interactive=false
#   become: yes
#   become_user: klide
#   args:
#     chdir: "{{ src_dir }}"
#     executable: /bin/bash
#   when: not ci

# - name: Run grunt
#   shell: grunt
#   become: yes
#   become_user: klide
#   args:
#     chdir: "{{ src_dir }}"
#     executable: /bin/bash
#   when: not ci

# - name: Get bower dependencies
#   command: bower install --config.interactive=false
#   become: no
#   args:
#     chdir: "{{ src_dir }}"
#   when: ci|bool

# - name: Run grunt
#   command: grunt
#   become: no
#   args:
#     chdir: "{{ src_dir }}"
#   when: ci|bool

# - name: Run Django South migrations
#   shell: . {{ web_virtualenv }}/bin/activate
#          && . /etc/profile.d/klee-web-environment.sh
#          && cd {{ application_dir }}
#          && python manage.py migrate --noinput

# - name: Run Django collectstatic
#   shell: . {{ web_virtualenv }}/bin/activate
#          && . /etc/profile.d/klee-web-environment.sh
#          && cd {{ application_dir }}
#          && python manage.py collectstatic --noinput

# - name: Create development admin user
#   shell: . /src/web/admin_psw.sh

# - name: Start django process
#   shell: supervisorctl reload

# BUILD AND RUN KLEE CONTAINER
- name: Build klee_web container
  command: docker build --file ./klee_web/Dockerfile -t klee_web .
  args:
    chdir: "{{ code_dir }}"

# - name: Build klee_web container
#   docker_image:
#     build:
#       path: "{{ code_dir }}"
#       dockerfile: "{{ application_dir }}/Dockerfile"
#     name: klee_web
#     force: yes

- name: Start docker klee-web
  docker_container:
    name: django_app
    image: klee_web
    networks: 
      - name: "{{ container_network }}"
    volumes:
      - /tmp:/tmp