---
# Install frontend dependencies

- name: "Add official NodeJS repo 6.x"
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  when: not ci
  tags: nodejs

- name: "Install node.js"
  apt: name=nodejs update_cache=yes
  when: not ci
  tags: nodejs

- name: "Install grunt-cli"
  npm: name=grunt-cli global=yes
  when: not ci

- name: "Install bower"
  npm: name=bower global=yes
  when: not ci

- name: "Install grunt-cli"
  npm: name=grunt-cli global=yes
  become: no
  when: ci|bool

- name: "Install bower"
  npm: name=bower global=yes
  become: no
  when: ci|bool

- name: "Install node dependencies"
  npm: path={{ src_dir }}
  become: yes
  become_user: klide
  when: not ci

- name: "Install node dependencies"
  npm: path={{ src_dir }}
  become: no
  when: ci|bool

- name: "Add brightbox ruby"
  apt_repository: repo='ppa:brightbox/ruby-ng'
  tags: setup

- name: "Install ruby"
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - ruby2.3
    - ruby2.3-dev

- name: "Set ruby2.3 to be the default one"
  shell: update-alternatives --set ruby /usr/bin/ruby2.3

- name: Install SASS
  command: gem install sass
