---
- name: Create Postgres volume
  docker_volume:
    name: postgres_data

- name: Run Postgres container
  docker_container:
    name: postgres_container
    image: postgres
    restart_policy: always
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_DB: "{{ db_name }}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - name: "{{ container_network }}"
    recreate: yes
